version: "3.9"

services:
  postgresql:
    image: "postgres:15.2-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: athena
      POSTGRES_PASSWORD: athena
      POSTGRES_DB: athena
  redis:
    image: "redis/redis-stack-server:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: --requirepass athena
  nginx:
    build:
      context: .
      target: nginx-stage
    image: athena-nginx:latest
    ports:
      - "80:80"
  api:
    build:
      context: .
      target: python-stage
    environment:
      ATHENA_MODE: api
    image: athena-api:latest
    ports:
      - "5000:5000"
