version: "3.9"

services:
  nginx:
    build:
      context: .
      target: nginx-stage
    image: billschumacher/athena-nginx:latest
    ports:
      - "80:80"

  api:
    build:
      context: .
      target: python-stage
    image: billschumacher/athena-api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis