version: "3.9"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: athena-tests:latest
    environment:
      ATHENA_MODE: test
    command: pytest
    env_file:
      - .env