WEATHER_TRAIN_DATA = [
    ("What is the weather like today?", {"intent": ["weather", ], "entities": []}),
    ("What is the weather like tomorrow?", {"intent": ["weather", ], "entities": []}),
    ("What is the weather like in London?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What is the weather like in Paris?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What is the weather like in New York?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What is the weather like in Berlin?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What is the weather like in Madrid?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like tomorrow?", {"intent": ["weather", ], "entities": []}),
    ("What will the weather be like in London?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like over the weekend?", {"intent": ["weather", ], "entities": []}),
    ("What will the weather be like in New York?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London over the weekend?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris over the weekend?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like in New York over the weekend?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin over the weekend?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid over the weekend?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London next week?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris next week?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like in New York next week?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin next week?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid next week?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London next week?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris next week?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like in New York for the next 24 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin for the next 24 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid for the next 24 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London for the next 24 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris for the next 24 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like in New York for the next 48 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin for the next 48 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid for the next 48 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London for the next 48 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris for the next 48 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What will the weather be like in New York for the next 72 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What will the weather be like in Berlin for the next 72 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What will the weather be like in Madrid for the next 72 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What will the weather be like in London for the next 72 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What will the weather be like in Paris for the next 72 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in London?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London over the weekend?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris over the weekend?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York over the weekend?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin over the weekend?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid over the weekend?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London next week?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris next week?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York next week?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin next week?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid next week?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London next week?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris next week?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York for the next 24 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin for the next 24 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid for the next 24 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London for the next 24 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris for the next 24 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York for the next 48 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin for the next 48 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid for the next 48 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London for the next 48 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris for the next 48 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("How's the weather in New York for the next 72 hours?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("How's the weather in Berlin for the next 72 hours?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("How's the weather in Madrid for the next 72 hours?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("How's the weather in London for the next 72 hours?", {"intent": ["weather", ], "entities": ["London"]}),
    ("How's the weather in Paris for the next 72 hours?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What's the weather like in London for the next 3 days?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What's the weather like in Paris for the next 3 days?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What's the weather like in New York for the next 3 days?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What's the weather like in Berlin for the next 3 days?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What's the weather like in Madrid for the next 3 days?", {"intent": ["weather", ], "entities": ["Madrid"]}),
    ("What's the weather like in London for the next week?", {"intent": ["weather", ], "entities": ["London"]}),
    ("What's the weather like in Paris for the next week?", {"intent": ["weather", ], "entities": ["Paris"]}),
    ("What's the weather like in New York for the next week?", {"intent": ["weather", ], "entities": ["New York"]}),
    ("What's the weather like in Berlin for the next week?", {"intent": ["weather", ], "entities": ["Berlin"]}),
    ("What's the weather like in Madrid for the next week?", {"intent": ["weather", ], "entities": ["Madrid"]}),
]

GREETING_TRAIN_DATA = [
    ("Hi", {"intent": ["greeting", ]}),
    ("Hello", {"intent": ["greeting", ]}),
    ("Hey", {"intent": ["greeting", ]}),
    ("Hi there", {"intent": ["greeting", ]}),
    ("Hello there", {"intent": ["greeting", ]}),
    ("Hey there", {"intent": ["greeting", ]}),
    ("Good morning", {"intent": ["greeting", ]}),
    ("Good afternoon", {"intent": ["greeting", ]}),
    ("Good evening", {"intent": ["greeting", ]}),
    ("Good day", {"intent": ["greeting", ]}),
    ("Good to see you", {"intent": ["greeting", ]}),
    ("Nice to see you", {"intent": ["greeting", ]}),
    ("Good to see you again", {"intent": ["greeting", ]}),
    ("Nice to see you again", {"intent": ["greeting", ]}),
]

GOODBYE_TRAIN_DATA = [
    ("Bye", {"intent": ["goodbye", ]}),
    ("See you later", {"intent": ["goodbye", ]}),
    ("See you soon", {"intent": ["goodbye", ]}),
    ("See you later alligator", {"intent": ["goodbye", ]}),
    ("See you later crocodile", {"intent": ["goodbye", ]}),
    ("See you later alligator in a while crocodile", {"intent": ["goodbye", ]}),
    ("Goodbye", {"intent": ["goodbye", ]}),
    ("Have a nice day", {"intent": ["goodbye", ]}),
    ("Have a nice day!", {"intent": ["goodbye", ]}),
    ("Have a nice day.", {"intent": ["goodbye", ]}),
]

INTENTION_DATA_SETS = [WEATHER_TRAIN_DATA, GREETING_TRAIN_DATA, GOODBYE_TRAIN_DATA]
INTENTIONS_TRAIN_DATA = [item for sublist in INTENTION_DATA_SETS for item in sublist]
